name: r2s Lean版openwrt ouhaiorg

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/r2s_lean.yml'
  schedule:
    - cron: '10 09 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.repository == 'klever1988/nanopi-openwrt'

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          tag_name: ${{ secrets.sec_token }}
          release_name: 自动发布 ${{ secrets.GITHUB_TOKEN }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
