on:
  push:
    branches:
      - master     
#  watch:
#    types: started
   
env:
  SSH_ACTIONS: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OpenWrt and release

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master    

#      - name: SSH connection to Actions
#        uses: P3TERX/debugger-action@master
#        if: env.SSH_ACTIONS == 'true'

      - name: Prepare Files
        run: |
          mkdir ./friendlywrt-rk3328/
          mkdir ./friendlywrt-rk3328/bin/
          cd ./friendlywrt-rk3328/bin
          curl -O http://us.ouhai.com/r.img
          
      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/bin/*.img

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
